# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 345f54bdb744d0b585baeefaee2dbdc2e76d989bc1c8f1e1b85ee3c6036c29a73eed1fb07fd63631d9c0e98e5523add6a911dd470a4efee133e04a0793802e7b

test:
  secret_key_base: a4b9e0cf860d2acc2b51c40d131ad3edda831879e1d69a02c014db8197e8733a10ec3a11fdbd34805c16fa09a0f3ef90e62b71fa03fa6f475b88f233679eaec8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
